### ISSUE TITLE
Make kanji results expandable, show elements, alternate meanings, etc

### ISSUE THREAD

**Issue by sschmidTU** [sschmidTU/mr-kanji-search-wtk#22]
Arrow right (collapsed) and down (expanded) would be nice, like this:
![image](https://user-images.githubusercontent.com/33069673/115813521-99581880-a3f3-11eb-8ab6-d5551f048308.png)
https://jsfiddle.net/ryanpcmcquen/wqz6v0xb/

edit: might be easier to use `<details><summary>` (HTML5)

<details><summary>jsfiddle content (in case it gets deleted)</summary>

HTML:

```html
<div class="panel panel-info">
  <div class="panel-heading collapsed" data-toggle="collapse" data-target="#bar">
    <i class="fa fa-fw fa-chevron-down"></i>
    <i class="fa fa-fw fa-chevron-right"></i>Foo
  </div>
  <div class="panel-body">
    <!-- The inside div eliminates the 'jumping' animation. -->
    <div class="collapse" id="bar">
      Bar.
    </div>
  </div>
</div>
```

CSS:
```css
.panel-heading.collapsed .fa-chevron-down,
.panel-heading .fa-chevron-right {
  display: none;
}

.panel-heading.collapsed .fa-chevron-right,
.panel-heading .fa-chevron-down {
  display: inline-block;
}

i.fa {
  cursor: pointer;
  margin-right: 5px;
}

.collapsed ~ .panel-body {
  padding: 0;
}
```

</details>

Showing the Kanji elements (#25) may need some refactors and/or restructuring of the data, see #24.
(e.g. 日 is always given as `sun, day`. but only `sun` would be needed.)
